theme: jekyll-theme-cayman
title: 3D printing shields ğŸ›¡ï¸ Information for makers
description: Information about producing emergency PPE for Irish healthcare centres during the COVID-19 crisis
github:
  is_project_page: false

